### ISSUE TITLE
Modify schemas outside of terraform and provider recognizing diff

### ISSUE THREAD

**Issue by ekeric13** [arkiaconsulting/terraform-provider-confluent-schema-registry#17]
Currently this provider works well for avro schemas that I only modify via terraform.

But if I make modifications outside of terraform it doesn't recognize them.

For example I created a new schema via the kafka api and it said there were no changes made:
```
Acquiring state lock. This may take a few moments...
schemaregistry_schema.heartbeat_v1: Refreshing state... [id=heartbeat_v1]

No changes. Your infrastructure matches the configuration.
```

I also deleted my existing schema via the kafka api and instead of trying to create a new one it gives me this error:
```
Acquiring state lock. This may take a few moments...
schemaregistry_schema.heartbeat_v1: Refreshing state... [id=heartbeat_v1]
╷
│ Error: 404 Not Found: Subject 'heartbeat_v1' not found. io.confluent.rest.exceptions.RestNotFoundException: Subject 'heartbeat_v1' not found.
│ io.confluent.rest.exceptions.RestNotFoundException: Subject 'heartbeat_v1' not found.
│ 	at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.subjectNotFoundException(Errors.java:77)
│ 	at io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource.getSchemaByVersion(SubjectVersionsResource.java:141)
│ 	at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
│ 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
│ 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
│ 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
```

**Comment by belint01** [comment]
It happened to me that entry in schema registry has been deleted and created during terraform apply but eventually terraform execution failed because of some other unrelated reason. Every subsequent terraform apply was failing because  schemaregistry provider couldn't refresh the state saying:

Subject 'foo' not found. io.confluent.rest.exceptions.RestNotFoundException: Subject 'foo' not found.
io.confluent.rest.exceptions.RestNotFoundException: Subject 'foo' not found.

It looks that schemaregistry provider is able to break the state on his own
